const Routes = {
    HOME_TABS: "HOME_TABS",

    FILMS_STACK: "FILMS_STACK",
    FILMS_SCREEN: "FILMS_SCREEN",
    FILM_DETAILS_SCREEN: "FILM_DETAILS_SCREEN",

    SPECIES_STACK: "SPECIES_STACK",
    SPECIES_SCREEN: "SPECIES_SCREEN",

    PLANETS_STACK: "PLANETS_STACK",
    PLANETS_SCREEN: "PLANETS_SCREEN",

    PEOPLE_STACK: "PEOPLE_STACK",
    PEOPLE_SCREEN: "PEOPLE_SCREEN",
};

export default Routes;
